# Generated by Django 5.0.1 on 2024-01-22 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Имя пользователя')),
                ('time_zone', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(12)], verbose_name='Часовой пояс')),
            ],
        ),
    ]
