# Generated by Django 4.2.9 on 2024-01-11 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название лиги')),
                ('league_code', models.CharField(max_length=5, verbose_name='Код лиги')),
                ('current_matchday', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Предстоящий тур')),
            ],
            options={
                'verbose_name': 'Лига',
                'verbose_name_plural': 'Лиги',
            },
        ),
        migrations.CreateModel(
            name='LeagueMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_match', models.CharField(max_length=100, verbose_name='Актуальный матч')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название команды')),
                ('wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Победы')),
                ('draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Ничьи')),
                ('loses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Поражения')),
                ('home_wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Домашние победы')),
                ('home_draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Домашние ничьи')),
                ('home_loses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Домашние поражения')),
                ('away_wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Гостевые победы')),
                ('away_draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Гостевые ничьи')),
                ('away_loses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Гостевые поражения')),
                ('form', models.CharField(blank=True, max_length=10, verbose_name='Форма команды')),
                ('home_form', models.CharField(blank=True, max_length=10, verbose_name='Домашняя форма команды')),
                ('away_form', models.CharField(blank=True, max_length=10, verbose_name='Гостевая форма команды')),
                ('goals', models.PositiveSmallIntegerField(default=0, verbose_name='Голы')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название команды')),
                ('url_id', models.IntegerField(unique=True, verbose_name='url_id')),
                ('shortname', models.CharField(max_length=5, verbose_name='Аббревиатура команды')),
                ('matches_played', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Матчей сыграно')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_stats.league', verbose_name='Лига')),
                ('stats_last_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_stats.statistics', verbose_name='Статистика команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['league__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='league',
            name='current_matches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_stats.leaguematches', verbose_name='Лига'),
        ),
    ]
