# Generated by Django 5.0.1 on 2024-01-18 10:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название лиги')),
                ('league_code', models.CharField(max_length=5, unique=True, verbose_name='Код лиги')),
                ('current_matchday', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Предстоящий тур')),
                ('start_date', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Дата и время начала тура')),
                ('end_date', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Дата и время окончания тура')),
            ],
            options={
                'verbose_name': 'Лига',
                'verbose_name_plural': 'Лиги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeagueMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Лиги')),
                ('current_match', models.CharField(max_length=100, verbose_name='Актуальный матч')),
                ('fulltime', models.CharField(blank=True, max_length=100, verbose_name='Счет матча')),
                ('date', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Дата и время матча')),
                ('finished', models.BooleanField(default=False, verbose_name='Проверка на завершенность матча')),
            ],
            options={
                'verbose_name': 'Матч лиги',
                'verbose_name_plural': 'Матчи лиги',
                'ordering': ['name', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('league', models.CharField(max_length=200, verbose_name='Лига')),
                ('team', models.CharField(max_length=200, verbose_name='Команда')),
                ('goals', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Кол-во голов')),
                ('penalty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Кол-во голов с пенальти')),
                ('assists', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Кол-во гол. передач')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['league', '-goals'],
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='количество запросов')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время начала тура')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название команды')),
                ('wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Победы')),
                ('draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Ничьи')),
                ('loses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Поражения')),
                ('home_wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Домашние победы')),
                ('home_draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Домашние ничьи')),
                ('home_loses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Домашние поражения')),
                ('away_wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Гостевые победы')),
                ('away_draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Гостевые ничьи')),
                ('away_loses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Гостевые поражения')),
                ('form', models.CharField(blank=True, max_length=10, verbose_name='Форма команды')),
                ('home_form', models.CharField(blank=True, max_length=10, verbose_name='Домашняя форма команды')),
                ('away_form', models.CharField(blank=True, max_length=10, verbose_name='Гостевая форма команды')),
                ('goals_scored', models.PositiveSmallIntegerField(default=0, verbose_name='Забитые голы')),
                ('goals_conceded', models.PositiveSmallIntegerField(default=0, verbose_name='Пропущенные голы')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название команды')),
                ('url_id', models.IntegerField(unique=True, verbose_name='url_id')),
                ('shortname', models.CharField(max_length=5, verbose_name='Аббревиатура команды')),
                ('league', models.CharField(max_length=100, verbose_name='Лига')),
                ('total_wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Общее кол-во побед')),
                ('total_loses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Общее кол-во поражений')),
                ('total_draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Общее кол-во ничьих')),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Кол-во очков')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['league', '-points'],
            },
        ),
    ]
