# Generated by Django 5.0.1 on 2024-01-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsUpdating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_updating', models.BooleanField(default=False)),
            ],
        ),
    ]
