# Generated by Django 4.2.9 on 2024-01-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['-id'], 'verbose_name': 'Лига', 'verbose_name_plural': 'Лиги'},
        ),
        migrations.AlterField(
            model_name='league',
            name='current_matches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_stats.leaguematches', verbose_name='Актуальные матчи'),
        ),
    ]
