# Generated by Django 4.2.9 on 2024-01-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0002_alter_league_options_alter_league_current_matches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['id'], 'verbose_name': 'Лига', 'verbose_name_plural': 'Лиги'},
        ),
    ]
