# Generated by Django 5.0.1 on 2024-01-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0002_isupdating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='away_draws',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='away_loses',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='away_wins',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='home_draws',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='home_loses',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='home_wins',
        ),
    ]
