# Generated by Django 4.2.9 on 2024-01-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0003_alter_league_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Код лиги'),
        ),
    ]
