# Generated by Django 5.0.1 on 2024-01-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0003_remove_statistics_away_draws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isupdating',
            name='league_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
