# Generated by Django 4.2.9 on 2024-01-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0004_alter_league_league_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguematches',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Название Лиги'),
            preserve_default=False,
        ),
    ]
