# Generated by Django 5.0.1 on 2024-01-19 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0004_isupdating_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во матчей'),
        ),
    ]
