# Generated by Django 4.2.9 on 2024-01-11 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0005_leaguematches_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='current_matches',
        ),
        migrations.AddField(
            model_name='leaguematches',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_stats.league', verbose_name='Лига'),
        ),
    ]
