# Generated by Django 5.0.1 on 2024-01-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='country',
            field=models.CharField(blank=True, max_length=20, verbose_name='Страна лиги'),
        ),
    ]
