# Generated by Django 4.2.9 on 2024-01-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0007_remove_leaguematches_league'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguematches',
            options={'ordering': ['name']},
        ),
    ]
