# Generated by Django 4.2.9 on 2024-01-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0008_alter_leaguematches_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='matchday_end_date',
            field=models.CharField(blank=True, max_length=15, verbose_name='Дата окончания тура'),
        ),
    ]
