# Generated by Django 5.0.1 on 2024-01-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0009_alter_requests_last_update_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
