# Generated by Django 5.0.1 on 2024-01-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0010_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL лого команды'),
        ),
    ]
