# Generated by Django 5.0.1 on 2024-01-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0012_alter_team_total_draws_alter_team_total_loses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo_url',
        ),
    ]
