# Generated by Django 5.0.1 on 2024-01-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0013_remove_team_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='adress',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес команды'),
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='team',
            name='founded',
            field=models.IntegerField(default=1, verbose_name='Год создания'),
        ),
        migrations.AddField(
            model_name='team',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Полное название команды'),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(blank=True, max_length=100, verbose_name='Стадион команды'),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сайт команды'),
        ),
    ]
