# Generated by Django 5.0.1 on 2024-01-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0014_team_adress_team_coach_team_founded_team_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стадион команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сайт команды'),
        ),
    ]
