# Generated by Django 4.2.9 on 2024-01-12 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0014_remove_team_matches_played'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['league__name', '-points'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Кол-во очков'),
        ),
        migrations.AddField(
            model_name='team',
            name='total_draws',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Общее кол-во ничьих'),
        ),
        migrations.AddField(
            model_name='team',
            name='total_loses',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Общее кол-во поражений'),
        ),
        migrations.AddField(
            model_name='team',
            name='total_wins',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Общее кол-во побед'),
        ),
    ]
