# Generated by Django 4.2.9 on 2024-01-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0015_alter_team_options_team_points_team_total_draws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguematches',
            name='date',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дата матча (МСК)'),
        ),
    ]
