# Generated by Django 5.0.1 on 2024-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0015_alter_team_adress_alter_team_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='founded',
            field=models.IntegerField(null=True, verbose_name='Год создания'),
        ),
    ]
