# Generated by Django 4.2.9 on 2024-01-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0017_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['league', '-goals']},
        ),
        migrations.AddField(
            model_name='leaguematches',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaguematches',
            name='fulltime',
            field=models.CharField(blank=True, max_length=100, verbose_name='Счет матча'),
        ),
    ]
