# Generated by Django 4.2.9 on 2024-01-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0018_alter_player_options_leaguematches_finished_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguematches',
            options={'ordering': ['name'], 'verbose_name': 'Матч лиги', 'verbose_name_plural': 'Матчи лиги'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['league', '-goals'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
    ]
