# Generated by Django 4.2.9 on 2024-01-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0019_alter_leaguematches_options_alter_player_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguematches',
            name='date',
        ),
    ]
