# Generated by Django 4.2.9 on 2024-01-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0020_remove_leaguematches_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguematches',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время матча'),
        ),
        migrations.AlterField(
            model_name='leaguematches',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Проверка на завершенность матча'),
        ),
    ]
