# Generated by Django 4.2.9 on 2024-01-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0021_leaguematches_date_alter_leaguematches_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguematches',
            options={'ordering': ['name', '-date'], 'verbose_name': 'Матч лиги', 'verbose_name_plural': 'Матчи лиги'},
        ),
    ]
