# Generated by Django 4.2.9 on 2024-01-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0022_alter_leaguematches_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='matchday_end_date',
        ),
    ]
