# Generated by Django 4.2.9 on 2024-01-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0023_remove_league_matchday_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время окончания тура'),
        ),
        migrations.AddField(
            model_name='league',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время начала тура'),
        ),
    ]
