# Generated by Django 4.2.9 on 2024-01-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0024_league_end_date_league_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='goals',
        ),
    ]
