# Generated by Django 4.2.9 on 2024-01-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0025_remove_statistics_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='goals_conceded',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Пропущенные голы'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='goals_scored',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Забитые голы'),
        ),
    ]
