# Generated by Django 4.2.9 on 2024-01-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0026_statistics_goals_conceded_statistics_goals_scored'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['league', '-points'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='stats_last_10',
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(max_length=100, verbose_name='Лига'),
        ),
    ]
