# Generated by Django 4.2.9 on 2024-01-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0027_alter_team_options_remove_team_stats_last_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания тура'),
        ),
        migrations.AlterField(
            model_name='league',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала тура'),
        ),
        migrations.AlterField(
            model_name='leaguematches',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время матча'),
        ),
    ]
