# Generated by Django 4.2.9 on 2024-01-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0028_alter_league_end_date_alter_league_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguematches',
            options={'ordering': ['name', 'date'], 'verbose_name': 'Матч лиги', 'verbose_name_plural': 'Матчи лиги'},
        ),
    ]
