# Generated by Django 4.2.9 on 2024-01-14 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0029_alter_leaguematches_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Дата и время окончания тура'),
        ),
        migrations.AlterField(
            model_name='league',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Дата и время начала тура'),
        ),
        migrations.AlterField(
            model_name='leaguematches',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Дата и время матча'),
        ),
    ]
