# Generated by Django 4.2.9 on 2024-01-17 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0030_alter_league_end_date_alter_league_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Число запросов')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления')),
            ],
        ),
    ]
