# Generated by Django 4.2.9 on 2024-01-17 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0031_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='counter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Число запросов'),
        ),
    ]
