# Generated by Django 4.2.9 on 2024-01-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0032_alter_requests_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
