# Generated by Django 4.2.9 on 2024-01-17 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_stats', '0033_delete_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='количество запросов')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время начала тура')),
            ],
        ),
    ]
